site_name: GitHub Actions Learning
site_description: Learning repository for GitHub Actions with MkDocs documentation
site_author: Matt Owen
site_url: https://mkowen1.github.io/github-actions-learning/

# Repository information
repo_name: github-actions-learning
repo_url: https://github.com/mkowen1/github-actions-learning
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  language: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  icon:
    repo: fontawesome/brands/github

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

# Plugins
plugins:
  - search:
      lang: en
  - git-revision-date-localized:
      enable_creation_date: true

# Page tree
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Basic Usage: getting-started/basic-usage.md
  - MkDocs Guide:
    - Material Theme: mkdocs-guide/material-theme.md
    - Mermaid Diagrams: mkdocs-guide/mermaid-diagrams.md
    - Advanced Features: mkdocs-guide/advanced-features.md
  - GitHub Actions:
    - Introduction: github-actions/introduction.md
    - Workflows: github-actions/workflows.md
  - Examples: examples.md

# Extra CSS and JS
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Copyright
copyright: Copyright &copy; 2025 Matt Owen
